/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "clock.h"
#include "i2c.h"
#include "TIM.h"
#include "gpio.h"
#include "oled.h"
#include "dht.h"
#include <stdio.h>

// Khai báo biến lưu trữ dữ liệu cảm biến
uint8_t temp = 0, humi = 0;
char str_temp[20];
char str_humi[20];
int main(void)
{
	RCC_Config() ;
		RCC_Enable_PortA() ;
		RCC_Enable_PortB() ;
		GPIO_Config(GPIOB,GPIO_PIN_6,GPIO_MODE_AF_OD) ;
		GPIO_Config(GPIOB,GPIO_PIN_7,GPIO_MODE_AF_OD) ;
		RCC_Enable_TIM2() ;
		RCC_Enable_TIM3() ;
		RCC_Enable_I2C01() ;
		TIM_Init(TIM2,64000) ;
		TIM_Init(TIM3, 64) ;
		I2C_Init() ;
		// Kh?i t?o h? th?ng, I2C và OLED
	    OLED_Init();
	    OLED_SetCursor(2, 10);      // Page 2, C?t 10
	    Oled_PutString("OLED 0.96 READY");
		Delay_ms(TIM2,3000) ;
		OLED_ClearBuffer();
	    OLED_Update(); // Xóa màn hình
	while(1) {
		if (DHT11_Read(&temp, &humi) == 0) {

		            // --- PHẦN 1: DÙNG BUFFER ĐỂ VẼ HÌNH ---
		            OLED_ClearBuffer();

		            // Vẽ khung cho dashboard bãi xe/môi trường
		            OLED_DrawRectangle(0, 0, 127, 63, 1);
		            // Vẽ một đường ngăn cách giữa tiêu đề và nội dung
		            OLED_DrawLine(0, 15, 127, 15, 1);

		            // Đẩy hình ảnh từ Buffer lên trước
		            OLED_Update();

		            // --- PHẦN 2: DÙNG HÀM CÓ SẴN ĐỂ GHI CHỮ (GHI THẲNG I2C) ---
		            // Lưu ý: Vì PutString của bạn không có tọa độ x, y trong đối số,
		            // bạn phải dùng OLED_SetCursor trước khi in.

		            // In tiêu đề
		            OLED_SetCursor(0, 20); // Page 0, Cột 20
		            Oled_PutString("SMART PARKING");

		            // In Nhiệt độ
		            sprintf(str_temp, "Temp: %d C", temp);
		            OLED_SetCursor(3, 10); // Page 3, Cột 10
		            Oled_PutString(str_temp);

		            // In Độ ẩm
		            sprintf(str_humi, "Humi: %d %%", humi);
		            OLED_SetCursor(5, 10); // Page 5, Cột 10
		            Oled_PutString(str_humi);

		        } else {
		            // Báo lỗi nếu không đọc được DHT11
		            OLED_SetCursor(4, 30);
		            Oled_PutString("DHT11 ERROR");
		        }

		        Delay_ms(TIM2, 2000);
		    }


}
